build:
  sut:
    image: appcelerator/docker-toolbox-node
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker login -u "$$DOCKER_HUB_LOGIN" -p "$$DOCKER_HUB_PASSWORD" -e "$$DOCKER_HUB_EMAIL"
    - ./drone.sh

debug: true

cache:
  mount:
    - .git

publish:
  docker:
    username: $$DOCKER_HUB_LOGIN
    password: $$DOCKER_HUB_PASSWORD
    email: $$DOCKER_HUB_EMAIL
    repo: appcelerator/telegraf
    dockerfile: Dockerfile
    tag: $$BRANCH
#    load: docker/image.tar
#    save:
#      destination: docker/image.tar
#      tag: $$BRANCH
    when:
      success: true
      event: push
      repo: appcelerator/docker-telegraf

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: amp-ci
    username: amp-drone-ci
    template: >
      build {{repo.name}} #{{ build.number }} finished with a {{ build.status }} status. ({{repo.full_name}}/[{{ build.branch }}] @{{build.author}} http://drone.amp.appcelerator.io:8000/{{repo.full_name}} )
