version: "2"

services:
  # system under test
  sut:
    build:
      context: .
      dockerfile: Dockerfile-SUT
    command: "/root/test/drone_test.sh"
    environment:
      DEBUG: app*
      AMP_SERVICE_URL: "http://amp-service:3000"
      AMP_LOG_URL: "http://amp-log:3000"
      AMP_CONSUL_URL: "http://consul:8500"
      AMP_ZOOKEEPER_ADDR: "zookeeper:2181"
    volumes:
      - ./src:/usr/src/app/src
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.git:/root/.git
    depends_on:
      - influxdb
      - telegraf

  # store
  consul:
    image: appcelerator/consul:latest-server
    hostname: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command:
      [ "-bootstrap"]

  # member
  amp-log-agent:
    image: appcelerator/amp-log-agent:latest
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "12201:12201/udp"
    environment:
      - DEBUG=app*
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - CONSUL=consul:8500

  amp-docker-agent:
    image: "appcelerator/amp-docker-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONSUL=consul:8500
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.amp-docker-agent"
    depends_on:
      - consul
      - amp-log-agent

  # swarm

  ## zakfka

  zookeeper:
    image: appcelerator/zookeeper:latest
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      CONSUL: consul:8500
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.zookeeper"
    depends_on:
      - consul
      - amp-log-agent

  kafka:
    image: appcelerator/kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      CONSUL: consul:8500
      TOPIC_LIST: "amp-logs amp-service-start amp-service-stop amp-service-terminate amp-docker-events amp-service-events"
    #logging:
    #  driver: gelf
    #  options:
    #    gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.kafka"
    depends_on:
      - zookeeper
      - amp-log-agent

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "8081:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      CONSUL: consul:8500
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.kafka-manager"
    depends_on:
      - zookeeper
      - amp-log-agent

  ## logging

  amp-log:
    image: appcelerator/amp-log:latest
    ports:
      - "5000:3000"
    environment:
      - DEBUG=app*,lib*
      - CONSUL=consul:8500
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.amp-log"
    depends_on:
      - cassandra
      - amp-log-agent

  amp-log-worker:
    image: appcelerator/amp-log-worker:latest
    ports:
      - "4018:3000"
    environment:
      - DEBUG=lib*,app*
      - CONSUL=consul:8500
    #logging:
    #  driver: gelf
    #  options:
    #    gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.amp-log-worker"
    depends_on:
      - amp-log-agent
      - kafka

  cassandra:
    image: appcelerator/cassandra
    ports:
    - 9042:9042
    environment:
      - SINGLE=true
      - CONSUL=consul:8500
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.cassandra"
    depends_on:
    - consul
    - amp-log-agent

  elasticsearch:
    image: appcelerator/elasticsearch-amp:latest
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      CONSUL: consul:8500
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.elasticsearch"
    depends_on:
    - consul
    - amp-log-agent

  kibana:
    image: kibana
    ports:
    - 5601:5601
    environment:
    - CONSUL=consul:8500
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    #logging:
    #  driver: gelf
    #  options:
    #    gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.kibana"
    depends_on:
    - elasticsearch
    - amp-log-agent

  ## log monitoring

  amp-monitor:
    image: appcelerator/amp-monitor:latest
    ports:
      - 6000:3000
    environment:
      - DEBUG=app*,lib*
      - CONSUL=consul:8500
    labels:
      - "ServiceUUId=system.amp-monitor"
    depends_on:
      - kafka
      - amp-log-agent

  ## services

  amp-service:
    image: appcelerator/amp-service
    ports:
      - "4000:3000"
    hostname: amp-service
    environment:
      DEBUG: "app*,api-*,-app:directoryrouter*,-app:route*"
      CONSUL: consul:8500
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.amp-service"
    depends_on:
    - kafka
    - amp-log-agent

  amp-service-worker:
    image: appcelerator/amp-service-worker
    ports:
      - "4001:3000"
    hostname: amp-service-worker
    environment:
      DEBUG: "app*,api-*,-app:directoryrouter*,-app:route*"
      CONSUL: consul:8500
      LOG_AGENT_HOST: "udp://localhost:12201"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.amp-service-worker"
    depends_on:
    - kafka
    - amp-log-agent

  ## monitoring (TIGK)

  telegraf:
    image: appcelerator/telegraf
    container_name: "telegraf"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/utmp:/var/run/utmp
    environment:
      - CONSUL=consul:8500
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TIMEOUT=20
      - INPUT_CPU_ENABLED=true
      - TAG_datacenter=dc1
      - TAG_type=core
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.telegraph"
    depends_on:
      - influxdb
      - amp-log-agent

  influxdb:
    image: appcelerator/influxdb:latest
    container_name: "influxdb"
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - CONSUL=consul:8500
      - FORCE_HOSTNAME=auto
      - PRE_CREATE_DB="telegraf"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.influxdb"
    depends_on:
    - consul
    - amp-log-agent

  grafana:
    image: appcelerator/grafana
    container_name: "grafana"
    volumes:
       - ./grafana-static:/etc/grafana/json
    ports:
     - "6001:3000"
    environment:
      - CONSUL=consul:8500
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PASS=changeme
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.grafana"
    depends_on:
      - influxdb
      - amp-log-agent

  kapacitor:
    image: appcelerator/kapacitor
    container_name: "kapacitor"
    environment:
      - CONSUL=consul:8500
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_HOSTNAME=auto
      - OUTPUT_SLACK_ENABLED=true
      - OUTPUT_SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
      - OUTPUT_SLACK_CHANNEL=kapacitor-test
      - OUTPUT_SLACK_GLOBAL=true
      - OUTPUT_SLACK_STATE_CHANGE_ONLY=true
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    labels:
      - "ServiceUUId=system.kapacitor"
    depends_on:
      - influxdb
      - amp-log-agent
